services:
  postgres:
    image: postgres:16-alpine
    container_name: prisma-perfil-alumno-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: prisma_user
      POSTGRES_PASSWORD: prisma_pass
      POSTGRES_DB: prisma_perfil_alumno
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
